"""initial schema

Revision ID: 1e23c734fb1d
Revises:
Create Date: 2026-04-18 23:17:57.995109

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1e23c734fb1d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
